package com.ailk.MybatisGenerator.dao;

import com.ailk.MybatisGenerator.entity.student;
import com.ailk.MybatisGenerator.entity.studentExample;
import java.util.List;

public interface StudentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat May 16 22:07:13 CST 2020
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat May 16 22:07:13 CST 2020
     */
    int insert(student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat May 16 22:07:13 CST 2020
     */
    int insertSelective(student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat May 16 22:07:13 CST 2020
     */
    List<student> selectByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat May 16 22:07:13 CST 2020
     */
    student selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat May 16 22:07:13 CST 2020
     */
    int updateByPrimaryKeySelective(student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat May 16 22:07:13 CST 2020
     */
    int updateByPrimaryKey(student record);
}